//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Diary()
        {
            this.People = new HashSet<Person>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Place_ID { get; set; }
        public Nullable<int> Quests_ID { get; set; }
        public Nullable<int> Items_ID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public string IngameDay { get; set; }
        public string Entry { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Place Place { get; set; }
        public virtual Quest Quest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> People { get; set; }
    }
}
