//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Diaries = new HashSet<Diary>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Clan_ID { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Rank { get; set; }
        public string Race { get; set; }
        public Nullable<bool> Dead { get; set; }
        public string Alignement { get; set; }
        public string Details { get; set; }
        public string Comment_2 { get; set; }
    
        public virtual Clan Clan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diary> Diaries { get; set; }
    }
}
